---
title: "Atmospheric CO2"
author: "Ben Bond-Lamberty and Corinne Hartin"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Atmospheric CO2}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

One common use for CMIP5 data, and the `RCMIP5` package, is to extract the global mean of some variable of interest for particular models, experiments, and/or ensembles. Here we give an example of this, computing the global mean CO2 value by year.

## Make sure the required data are present

As the package documentation notes (see e.g. http://gitcom.com/JGCRI/RCMIP) you first have to download the necessary from an Earth System Grid Federation node; RCMIP5 won't do this for you. Assuming this step is complete, then, we check to make sure all the data we'll need are present. First load information about all the CMIP5 files available:
```
library(RCMIP5)
c5files <- getFileInfo("~/location/of/cmip5/files/"")
```

By default, `getFileInfo` will recursively scan the entire directory tree and return a data frame containing the following information:

- File path
- File name
- Variable name
- Domain
- Model
- Experiment (typically historical, rcp45, rcp85, etc.)
- Ensemble
- Time^[Unless it's an 'fx' (fixed) domain file, with no time dimension.]
- Size (kb)

We're interested in the CO2 files; more specifically, we want to know whether all the necessary files have been downloaded.

```
co2files <- subset(c5files, variable=="co2")
co2filechk <- checkTimePeriod(co2files)
co2filechk[-1]  # don't display the file path
```

For the CMIP5 data we have^[Again, this depends on what you've downloaded from the ESGF! Naively running the commands in this vignette, without the appropriate CMIP5 data, will produce nothing but errors.], this produces the following output:

TODO - get a data frame from CH; dput it; use a chunk to print output.


## Load the data


```
co2 <- loadCMIP5("co2", "CMCC-CESM", "co2", path="~/location/of/cmip5/files/")
```

Note about yearRange

## Look at data - summary, etc.

```
summary(co2)
```

## Compute global means

Load the correct area file.
makeGlobalStat

## Export the data for further processing

We can simply use `as.data.frame` to convert our `cmip5data` object to a standard data frame:

```
co2g_df <- as.data.frame(co2g)

## Processing many different models, experiments, etc.


