---
title: "Download management"
author: "Kathe Todd-Brown"
date: "`r Sys.Date()`”
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Download management}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

For model inter-comparison projects it is frequently necessary to download a large number of files from the [CMIP5] (http://cmip-pcmdi.llnl.gov/cmip5/) repository making it challenging to know which files were downloaded and whether the complete ensemble was pulled for a given experiment-model-variable combination. While RCMIP5 will not download simulation result directly from the [Earth System Federation Grid] (pcmdi9.llnl.gov/esgf-web-fe/), there are several tools to help the user manage a large number of data files from CMIP5.

```
library(RCMIP5)
allDownloads <- getFileInfo(‘/path/to/CMIP5/downloads/‘)
```

By default, `getFileInfo` will recursively scan the entire directory tree and return a data frame containing the following information extracted from the file names:

- File path
- File name
- Variable name
- Domain
- Model
- Experiment (typically historical, rcp45, rcp85, etc.)
- Ensemble
- Time
- Size (kb)

## Look for empty files
Occasionally a download will be interrupted for some reason resulting in an empty file. These will have size 0kb and can be listed using:

```
allDownloads[allDownloads$fileSize == 0,]
```

The files can then be removed and downloaded again either in the directory directly or through `file.remove(as.character(allDownloads[allDownloads$fileSize == 0, 1]))`

## Check time points

Similarly, even if all the files are non-zero several CMIP5 centers will break up their ensembles into multiple NetCDF files. 
```
yrCheck <- checkTimePeriod(allDownloads)
```

While not fool proof, there are some basic checks that RCMIP5 can do to see if anything is obviously missing from these files. 
```
badCheck <- yrCheck[!yrCheck$allHere & is.finite(yrCheck$allHere),]
```

There are several known shortcomings due to the fact that these checks are based entirely on the filename. Specifically, this function
1. misses missing files from the beginning or end of the time period.
2. misses mismatched time periods between ensembles.
3. flages as unknown any sub-monthly time period because different models have different calendars. `yrCheck[is.na(yrCheck$allHere),]`


## Subsetting information
Often you’ll want to check which model-variable combinations are downloaded for a given experiment.
```
library(reshape2)
downloadSummary <- allDownloads[allDownloads$variable %in% c(‘cSoil’, ‘cVeg’) &
                                allDownloads$experiment %in% '1pctCO2',
                                c('variable', 'model')]

downloadSummary <- dcast(downloadSummary, model ~ variable,
                         fun.aggregate=length)
```

